FROM node:22-bookworm

WORKDIR /usr/src/http

ARG BACKEND_URL
ENV DATABASE_URL=$BACKEND_URL

COPY package.json ./package.json
COPY packages ./packages

COPY turbo.json ./turbo.json

COPY ./apps/web ./apps/web
RUN npm install -g npm@11.18.0
RUN npm install 

RUN npm run prisma-generate
RUN npm run build:web

EXPOSE 3000

CMD ["npm","run","start:web"]
