FROM node:22-bookworm

WORKDIR /usr/src/http

RUN npm install -g npm@11.18.0

COPY package.json ./package.json
COPY packages ./packages

COPY turbo.json ./turbo.json

COPY apps/http ./apps/http

RUN npm install
RUN npm run prisma-generate
RUN npm run createddisp

EXPOSE 3001

CMD ["npm","run","start:http"]