FROM oven/bun:1

WORKDIR /usr/src/http

ARG DATABASE_URL
COPY package.json ./package.json
COPY packages ./packages

COPY turbo.json ./turbo.json

COPY ./apps/web ./apps/web

RUN npm install
RUN npm run prisma-generate
RUN BACKEND_URL=${BACKEND_URL} npm run build:web

EXPOSE 3000

CMD ["npm","run","start:web"]
