FROM node:22-bookworm

WORKDIR /usr/src/http

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

COPY package.json ./package.json
COPY packages ./packages

COPY turbo.json ./turbo.json

COPY apps/web ./apps/web
RUN npm install -g npm@11.18.0
RUN npm install 

RUN npm run prisma-generate
RUN npm run createddisp

RUN if [ -z "$DATABASE_URL" ]; then \
      echo "❌ DATABASE_URL is EMPTY"; \
    else \
      echo "✅ DATABASE_URL is set, length: ${$DATABASE_URL}"; \
    fi

RUN npm run build:web

EXPOSE 3000

CMD ["npm","run","start:web"]
