FROM node:22-bookworm

WORKDIR /usr/src/http

COPY package.json ./package.json
COPY packages ./packages

COPY turbo.json ./turbo.json

COPY ./apps/http ./apps/http

RUN npm install
RUN npm run prisma-generate

EXPOSE 3001

CMD ["npm","run","start:http"]