name: Deploy the backend

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.frontend
          build-args:
            - DATABASE_URL= ${{DOCKERHUB_DATABASE}}
          push: true
          tags: lakhwinder97187/turbo-july-frontend:${{ github.sha }}
          ## step to deploy on virtual machine