name: Deploy the backend

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: lakhwinder97187/turbo-july-backend:${{ github.sha }}
          ## step to deploy on virtual machine

      - name: Deploy the backend
        run: |
          set -e
          trap 'rm -f ~/askpass.sh ~/ssh_key' EXIT
          printf '%s\n' "${{secrets.SSH_PRIVATE_KEY}}" > ~/ssh_key
          
          chmod 600 ~/ssh_key

          printf '#!/bin/sh\necho "%s"\n' "${{secrets.SSH_PHASPHRASE}}" > ~/askpass.sh
          chmod 700 ~/askpass.sh

          eval "{ssh-agent -s}"
          export SSH_ASKPASS=~/askpass.sh
          export SSH_ASKPASS_REQUIRE=force
          setsid ssh-add ~/ssh_key < /dev/null
          
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev\null/
            azureuser@172.197.240.14
            "docker stop backend || true
             docker rm backend || true
             docker run --name backend -d -p 3001:3001 lakhwinder97187/turbo-july-backend:${{github.sha}}"