name: Deploy the frontend

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.frontend
          build-args: |
            DATABASE_URL= ${{secrets.DOCKERHUB_DATABASE}}
          push: true
          tags: lakhwinder97187/turbo-july-frontend:${{ github.sha }}
          ## step to deploy on virtual machine
      - name: Deploy to the VM
        run: |
          echo "${{secrets.SSH_PRIVATE_KEY}}" &> ~/ssh_key
          chmod 700 /home/runner/ssh_key

          eval "$(ssh-agent -s)"
          ssh-add ~/ssh-key <<< "${{ secrets.SSH_PHASPHRASE }}"

          ssh -o StrictHostKeyChecking=no -i ~/ssh_key azureuser@172.197.240.14 -t "docker stop frontend && docker run --name Frontend -d -p 3000:3000 lakhwinder97187/turbo-july-frontend:${{github.sha}}"